title: COLLODI-1
description: A state-of-the-art pipeline for Anything-To-3D

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
